// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0
// source: message.sql

package db

import (
	"context"
)

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (
  "from",
  message
) VALUES (
  $1, $2
) RETURNING id, "from", message, created_at
`

type CreateMessageParams struct {
	From    string `json:"from"`
	Message string `json:"message"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, createMessage, arg.From, arg.Message)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.From,
		&i.Message,
		&i.CreatedAt,
	)
	return i, err
}

const getMessage = `-- name: GetMessage :one
SELECT id, "from", message, created_at FROM messages ORDER BY created_at DESC LIMIT 1
`

func (q *Queries) GetMessage(ctx context.Context) (Message, error) {
	row := q.db.QueryRow(ctx, getMessage)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.From,
		&i.Message,
		&i.CreatedAt,
	)
	return i, err
}
